apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: deploy
on:
  workflow_call:
    inputs:
      artifact-id:
        type: string
        required: true
      artifactVersion:
        type: string
        required: true
      environment:
        type: string
        required: true
  workflow_dispatch:
    inputs:
      artifact-id:
        type: string
        required: true
      artifactVersion:
        type: string
        required: true
        default: latest
      environment:
        type: string
        required: true
        default: j-hackers-k3s
env:
  APP_NAME: microhacker-web
jobs:
  deploy:
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1
        with:
          repository: jalts-808/j-hackers-web
      - uses: cloudbees-days/setup-kubeconfig
        name: Set kubeconfig
        with:
          kubeconfig: ${{ secrets.kubeconfig }}
      - id: install-chart
        name: Install helm chart
        uses: cloudbees-io/helm-install@v1
        with:
          chart-location: ${{ cloudbees.workspace }}/chart
          release-name: ${{ env.APP_NAME }}
          namespace: ${{ vars.namespace }}
          values: |
            image:
              repository: ${{ secrets.DOCKERHUB_USER }}/hackers-web
              tag: ${{ inputs.artifactVersion }}
            hostname: ${{ vars.host_prefix }}hackers-web.54.201.69.176.nip.io
            ingress:
              className: traefik
            config:
              fmKey: ${{ secrets.FM_TOKEN }}
              apiUrl: http://${{ vars.host_prefix }}hackers-api.54.201.69.176.nip.io/api
              authUrl: http://${{ vars.host_prefix }}hackers-auth.54.201.69.176.nip.io
      - name: Register deployed artifact
        if: ${{ inputs.artifact-id != 'test-deploy' && inputs.artifact-id != 'manual' && inputs.artifact-id != '' }}
        uses: cloudbees-io/register-deployed-artifact@v2
        with:
          artifact-id: ${{ inputs.artifact-id }}
          target-environment: ${{ inputs.environment }}
      - name: Publish evidence
        uses: cloudbees-io/publish-evidence-item@v1
        with:
          content: |-
            ## Deployed to ${{ inputs.environment }}
            [Frontend](http://${{ vars.host_prefix }}hackers-web.54.201.69.176.nip.io/)

            Running hackers-web:${{ inputs.artifactVersion }}
          format: MARKDOWN
